Platform/demo/demo.c, Services/service_response.c, Services/time_management_service.c, main.c
Minor bug fixes to fix the task instantiation.
=> fix: fixes logic for starting tasks, use ex2_log

makefile
Add makefile for building library
=> makefile for services

Platform/demo/hal/demo_hal.c, Services/service_response.c
=> Add obc platform

Services/service_response.c, Services/service_utilities.c, Services/service_utilities.h, Services/time_management_service.c
Convert from Network to host byte order on the incoming bytes
Get and set time on TMS570 successfully
- [] Docker image builds with the changes
- [] Docker image runs with the changes
- [] Can send commands from a mocked ground station
- [] Changes have been reviewed
=> fix: deal with endianness on TX/RX data bytes

Services/include/housekeeping/housekeeping_service.h, Services/source/housekeeping/housekeeping_service.c
=> Creation of the entire housekeeping service

Services/source/housekeeping/housekeeping_service.c
- [ X] Docker image or CCS Project builds with the changes
- [ X] Docker image or CCS Project runs with the changes
=> hk bug fixes. no longer causes reset in background

Services/source/communication/communication_service.c
=> Single return after vPortFree()s comms_service

Services/include/housekeeping/housekeeping_service.h, Services/source/housekeeping/housekeeping_service.c
=> Housekeeping bug fixes

Services/source/time_management/time_management_service.c
Not sure why I made it so high
=> lower priority of GPS related tasks

Services/source/housekeeping/housekeeping_service.c
=> prevent reboot from erasing housekeeping data

Services/source/updater/updater.c
=> fix variable name

Services/include/logger/logger_service.h, Services/source/housekeeping/housekeeping_service.c, Services/source/logger/logger_service.c
=> Logger gs commands

Services/source/time_management/time_management_service.c
=> Make time management use RTC

Services/source/housekeeping/housekeeping_service.c
=> Hk storage redesign

Services/include/housekeeping/housekeeping_service.h, Services/source/housekeeping/housekeeping_service.c
- [ x] Docker image or CCS Project builds with the changes
=> Hk add more services

Services/include/logger/logger_service.h, Services/source/housekeeping/housekeeping_service.c, Services/source/logger/logger_service.c
=> updates to logger service

Services/include/housekeeping/housekeeping_service.h, Services/source/housekeeping/housekeeping_service.c
=> remove outdated names from files

Services/include/services.h, Services/source/adcs/adcs_service.c, Services/source/communication/communication_service.c, Services/source/general.c, Services/source/housekeeping/housekeeping_service.c, Services/source/logger/logger_service.c, Services/source/time_management/time_management_service.c, Services/source/updater/updater.c
=> Make services use watchdog

Services/source/time_management/time_management_service.c
=> remove RTC mock from time_management

Services/source/adcs/adcs_service.c
I don't know how this built for anybody.
=> change config parameter to pointer

Services/include/housekeeping/housekeeping_service.h, Services/source/housekeeping/housekeeping_service.c, Services/source/updater/updater.c
housekeeping.c wasn't compiling because EPSget_hk had added startup telemetry. I added that struct to the global housekeeping struct
=> Update housekeeping to use new EPSget_hk

Services/include/communication/communication_service.h, Services/include/housekeeping/housekeeping_service.h, Services/source/communication/communication_service.c, Services/source/housekeeping/housekeeping_service.c
=> Thomas dev

Services/include/communication/communication_service.h, Services/include/housekeeping/housekeeping_service.h, Services/source/communication/communication_service.c, Services/source/housekeeping/housekeeping_service.c, Services/source/time_management/time_management_service.c
=> Prototype Flatsat Testing

Services/source/housekeeping/housekeeping_service.c
I noticed that housekeeping was including a file from the uhf software, creating a weird dependency situation. Got a bit carried away and removed everything unnecessary
=> Remove unneeded includes from housekeeping

Services/source/housekeeping/housekeeping_service.c, Services/source/time_management/time_management_service.c
=> Flatsat updates
